const fs = require("fs");
const path = require("path");

const extras = {
  "cron-expressions-guide": '<h2>Quick Reference</h2>\n<table>\n<thead><tr><th>Schedule</th><th>Expression</th></tr></thead>\n<tbody>\n<tr><td>Every 5 minutes</td><td><code>*/5 * * * *</code></td></tr>\n<tr><td>Hourly</td><td><code>0 * * * *</code></td></tr>\n<tr><td>Weekdays 9 AM</td><td><code>0 9 * * 1-5</code></td></tr>\n<tr><td>Midnight 1st</td><td><code>0 0 1 * *</code></td></tr>\n</tbody>\n</table>\n\n<h2>Testing Cron Before Deployment</h2>\n<p>Before deploying, verify your expression shows the expected execution times. Use our <a href="/tools/cron-parser/">Cron Expression Parser</a>. For production cron debugging, check execution logs — most cron daemons log to syslog. When migrating between platforms, verify field count: standard Unix uses 5 fields; Quartz (Java) uses 6 or 7. Never assume a cron expression from one platform works unchanged on another.</p>',

  "lorem-ipsum-guide": '<h2>Quick Reference</h2>\n<table>\n<thead><tr><th>Use Case</th><th>Paragraphs</th><th>Format</th></tr></thead>\n<tbody>\n<tr><td>Hero section</td><td>1</td><td>Plain text</td></tr>\n<tr><td>Blog template</td><td>3-5</td><td>HTML</td></tr>\n<tr><td>Long-form article</td><td>5-10</td><td>HTML</td></tr>\n</tbody>\n</table>\n\n<h2>The Ethics of Placeholder Text</h2>\n<p>Lorem Ipsum is a tool, not a solution. When you present a mockup with Lorem Ipsum, you are saying "the words here do not matter yet." When you launch with Lorem Ipsum still in place, users see an unfinished site. The most professional use is the briefest: fill space during design, replace with real content before anyone outside the team sees it.</p>',

  "number-bases-guide": '<h2>Quick Reference</h2>\n<table>\n<thead><tr><th>Decimal</th><th>Binary</th><th>Octal</th><th>Hex</th></tr></thead>\n<tbody>\n<tr><td>10</td><td>1010</td><td>12</td><td>A</td></tr>\n<tr><td>15</td><td>1111</td><td>17</td><td>F</td></tr>\n<tr><td>16</td><td>10000</td><td>20</td><td>10</td></tr>\n<tr><td>255</td><td>11111111</td><td>377</td><td>FF</td></tr>\n</tbody>\n</table>\n\n<h2>Number Bases in Protocols and File Formats</h2>\n<p>Network byte order is essentially a base-256 positional system. IPv4 subnet masks are binary patterns. Unicode code points are conventionally hex: U+0041 is A, U+1F600 is the grinning face emoji. ASCII codes are documented in decimal, hex, and octal. The more systems you work with, the more number bases you will encounter — they are the shared vocabulary between human-readable representation and machine-readable data.</p>',

  "sql-formatting-guide": '<h2>Quick Reference</h2>\n<table>\n<thead><tr><th>Rule</th><th>Example</th></tr></thead>\n<tbody>\n<tr><td>Keywords uppercase</td><td>SELECT, FROM, WHERE</td></tr>\n<tr><td>One clause per line</td><td>Each major clause at left margin</td></tr>\n<tr><td>Indent sub-clauses</td><td>2 spaces for JOIN, WHERE</td></tr>\n</tbody>\n</table>\n\n<h2>Anti-Patterns That Formatting Reveals</h2>\n<p>Consistent formatting makes structural problems visible. A SELECT * stands out because the * is alone on its indented line. A missing JOIN condition is obvious when every other JOIN has an ON clause. Nested subqueries that should be CTEs look visually awkward. If your formatting convention is consistent, structural problems become visually apparent the way a proofreader notices a misspelled word — you do not need to read the query to know something is wrong.</p>',

  "ssl-certificates-guide": '<h2>Quick Reference</h2>\n<table>\n<thead><tr><th>Type</th><th>Validation</th><th>Cost</th></tr></thead>\n<tbody>\n<tr><td>DV</td><td>Domain control only</td><td>Free-$10/yr</td></tr>\n<tr><td>OV</td><td>DV + org verification</td><td>~$50-100/yr</td></tr>\n<tr><td>EV</td><td>Extensive verification</td><td>~$100-300/yr</td></tr>\n</tbody>\n</table>\n\n<h2>Automating Certificate Management</h2>\n<p>Manual renewal does not scale. Let us Encrypt and the ACME protocol have made automated issuance standard. Tools like Certbot, acme.sh, and Caddy handle the entire lifecycle. For Kubernetes, cert-manager automates certificate management. If you are still manually generating CSRs, downloading files, uploading to servers, and setting calendar reminders — you are spending time on something a cron job should handle.</p>',

  "string-escaping-guide": '<h2>Quick Reference</h2>\n<table>\n<thead><tr><th>Sequence</th><th>Character</th></tr></thead>\n<tbody>\n<tr><td>\\n</td><td>Newline (LF)</td></tr>\n<tr><td>\\t</td><td>Horizontal tab</td></tr>\n<tr><td>\\"</td><td>Double quote</td></tr>\n<tr><td>\\\\</td><td>Backslash</td></tr>\n</tbody>\n</table>\n\n<h2>Escaping in Template Systems</h2>\n<p>Modern frameworks handle escaping automatically until you bypass them. Reacts JSX escapes all string content. Vues templates auto-escape. Handlebars auto-escapes. The vulnerabilities come when developers bypass the framework with innerHTML, string concatenation, or custom render functions. Trust your framework; verify when you bypass it. The escaping is context-aware: HTML body gets HTML-escaped, attributes get attribute-escaped, URLs get URL-encoded.</p>',

  "text-diffing-guide": '<h2>Quick Reference</h2>\n<table>\n<thead><tr><th>Command</th><th>Purpose</th></tr></thead>\n<tbody>\n<tr><td>git diff</td><td>Unstaged working tree changes</td></tr>\n<tr><td>git diff --staged</td><td>Staged changes before commit</td></tr>\n<tr><td>git diff main...feature</td><td>Branch divergence from main</td></tr>\n</tbody>\n</table>\n\n<h2>When Diffs Are the Wrong Tool</h2>\n<p>Diffs work well for source code and structured text. They work poorly for binary files — the output is meaningless. They are semantically unaware: moving a function shows as deletion and addition with no indication the code is the same. Git can detect renamed files with --find-renames, but this is heuristic. For semantically meaningful comparisons — did this function behavior change? — you need tests, not diffs.</p>',

  "url-slugs-guide": '<h2>Quick Reference</h2>\n<table>\n<thead><tr><th>Rule</th><th>Do</th><th>Dont</th></tr></thead>\n<tbody>\n<tr><td>Case</td><td>my-page</td><td>My-Page</td></tr>\n<tr><td>Separator</td><td>my-page</td><td>my_page</td></tr>\n<tr><td>Special chars</td><td>cafe</td><td>caf%C3%A9</td></tr>\n</tbody>\n</table>\n\n<h2>Handling Slug Conflicts</h2>\n<p>When two pages would share the same slug, you need disambiguation. Common approaches: numeric suffixes (my-post-2), date prefixes (2024-01-my-post), or category segments (tech/my-post). WordPress uses numeric suffixes. Apply your strategy consistently, and check for conflicts before publishing. A duplicate slug that silently overwrites an existing page is a content management bug that can go unnoticed for months.</p>',

  "url-structure-guide": '<h2>Quick Reference</h2>\n<table>\n<thead><tr><th>Component</th><th>Example</th><th>Required</th></tr></thead>\n<tbody>\n<tr><td>Scheme</td><td>https://</td><td>Yes</td></tr>\n<tr><td>Hostname</td><td>example.com</td><td>Yes</td></tr>\n<tr><td>Port</td><td>:8080</td><td>No</td></tr>\n<tr><td>Pathname</td><td>/path</td><td>No</td></tr>\n<tr><td>Search</td><td>?q=hello</td><td>No</td></tr>\n<tr><td>Hash</td><td>#section</td><td>No</td></tr>\n</tbody>\n</table>\n\n<h2>URL Design for REST APIs</h2>\n<p>Use plural nouns for collections (/users, not /user). Nested paths for relationships (/users/123/orders). Query parameters for filtering and pagination. Avoid verbs — the HTTP method already describes the action. Avoid deeply nested resources beyond two levels. A well-designed URL structure makes an API intuitive to explore and easy to document.</p>',

  "user-agent-guide": '<h2>Quick Reference</h2>\n<table>\n<thead><tr><th>Browser</th><th>Token</th></tr></thead>\n<tbody>\n<tr><td>Chrome</td><td>Chrome/ + version</td></tr>\n<tr><td>Safari</td><td>Version/ + Safari/</td></tr>\n<tr><td>Firefox</td><td>Firefox/ + version</td></tr>\n<tr><td>Edge</td><td>Edg/ + version</td></tr>\n</tbody>\n</table>\n\n<h2>The Future: User-Agent Client Hints</h2>\n<p>Googles User-Agent Client Hints (UA-CH) replaces the monolithic UA string with structured hints. The browser sends minimal high-entropy data only when the server requests it via Accept-CH. Chrome supports UA-CH since version 89. Other browsers have been slower to adopt. The traditional UA string remains the universal fallback but is being deprecated. New applications should support both — structured hints when available, UA string parsing as fallback.</p>'
};

const guidesDir = "src/pages/guides";
let updated = 0;
for (const guideId in extras) {
  const f = path.join(guidesDir, guideId + ".astro");
  if (!fs.existsSync(f)) continue;
  let c = fs.readFileSync(f, "utf8");
  c = c.replace("\n</div>\n`", extras[guideId] + "\n</div>\n`");
  fs.writeFileSync(f, c);
  updated++;
}
console.log("Appended to " + updated + " guides");
